2024-10-20 15:39:03,292 INFO Mail service setup successfully: /home/frank/eazy_manage_backend/./app.py 89
2024-10-20 15:39:03,305 INFO App created successfully: /home/frank/eazy_manage_backend/./app.py 99
2024-10-20 16:19:34,268 INFO Logging setup successfully: /home/frank/eazy_manage_backend/./app.py 43
2024-10-20 16:19:34,269 INFO DataBase set up successfully: /home/frank/eazy_manage_backend/./app.py 55
2024-10-20 16:19:34,597 INFO database set up successfully: /home/frank/eazy_manage_backend/./app.py 60
2024-10-20 16:19:34,611 INFO Migrations set up successfully: /home/frank/eazy_manage_backend/./app.py 68
2024-10-20 16:19:34,638 INFO Blueprints registered successfully: /home/frank/eazy_manage_backend/./app.py 76
2024-10-20 16:19:34,639 INFO Mail service setup successfully: /home/frank/eazy_manage_backend/./app.py 89
2024-10-20 16:19:34,639 INFO App created successfully: /home/frank/eazy_manage_backend/./app.py 99
2024-10-20 16:22:26,572 INFO Logging setup successfully: /home/frank/eazy_manage_backend/./app.py 43
2024-10-20 16:22:26,573 INFO DataBase set up successfully: /home/frank/eazy_manage_backend/./app.py 55
2024-10-20 16:22:26,869 INFO database set up successfully: /home/frank/eazy_manage_backend/./app.py 60
2024-10-20 16:22:26,890 INFO Migrations set up successfully: /home/frank/eazy_manage_backend/./app.py 68
2024-10-20 16:22:26,934 INFO Blueprints registered successfully: /home/frank/eazy_manage_backend/./app.py 76
2024-10-20 16:22:26,936 INFO Mail service setup successfully: /home/frank/eazy_manage_backend/./app.py 89
2024-10-20 16:22:26,939 INFO App created successfully: /home/frank/eazy_manage_backend/./app.py 99
2024-10-20 16:23:22,794 WARNING Error fetching tasks: /home/frank/eazy_manage_backend/api/v1/routes/employees.py 32
Traceback (most recent call last):
  File "/home/frank/eazy_manage_backend/api/v1/routes/employees.py", line 25, in get_tasks
    tasks = db.session.query(Tasks).offset(offset).limit(limit).filter(Tasks.user_id == user_id, Tasks.status == status).all()
  File "<string>", line 2, in filter
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/sql/base.py", line 280, in _generative
    x = fn(self, *args, **kw)
  File "<string>", line 2, in filter
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/base.py", line 302, in generate
    assertion(self, fn.__name__)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 442, in _no_limit_offset
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Query.filter() being called on a Query which already has LIMIT or OFFSET applied.  Call filter() before limit() or offset() are applied.
2024-10-20 16:23:47,573 WARNING Error fetching tasks: /home/frank/eazy_manage_backend/api/v1/routes/employees.py 32
Traceback (most recent call last):
  File "/home/frank/eazy_manage_backend/api/v1/routes/employees.py", line 25, in get_tasks
    tasks = db.session.query(Tasks).offset(offset).limit(limit).filter(Tasks.user_id == user_id, Tasks.status == status).all()
  File "<string>", line 2, in filter
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/sql/base.py", line 280, in _generative
    x = fn(self, *args, **kw)
  File "<string>", line 2, in filter
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/base.py", line 302, in generate
    assertion(self, fn.__name__)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 442, in _no_limit_offset
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Query.filter() being called on a Query which already has LIMIT or OFFSET applied.  Call filter() before limit() or offset() are applied.
2024-10-20 16:27:46,190 INFO Logging setup successfully: /home/frank/eazy_manage_backend/./app.py 43
2024-10-20 16:27:46,191 INFO DataBase set up successfully: /home/frank/eazy_manage_backend/./app.py 55
2024-10-20 16:27:46,297 INFO database set up successfully: /home/frank/eazy_manage_backend/./app.py 60
2024-10-20 16:27:46,302 INFO Migrations set up successfully: /home/frank/eazy_manage_backend/./app.py 68
2024-10-20 16:27:46,312 INFO Blueprints registered successfully: /home/frank/eazy_manage_backend/./app.py 76
2024-10-20 16:27:46,312 INFO Mail service setup successfully: /home/frank/eazy_manage_backend/./app.py 89
2024-10-20 16:27:46,313 INFO App created successfully: /home/frank/eazy_manage_backend/./app.py 99
2024-10-20 16:28:08,502 INFO Logging setup successfully: /home/frank/eazy_manage_backend/./app.py 43
2024-10-20 16:28:08,504 INFO DataBase set up successfully: /home/frank/eazy_manage_backend/./app.py 55
2024-10-20 16:28:08,655 INFO database set up successfully: /home/frank/eazy_manage_backend/./app.py 60
2024-10-20 16:28:08,674 INFO Migrations set up successfully: /home/frank/eazy_manage_backend/./app.py 68
2024-10-20 16:28:08,719 INFO Blueprints registered successfully: /home/frank/eazy_manage_backend/./app.py 76
2024-10-20 16:28:08,721 INFO Mail service setup successfully: /home/frank/eazy_manage_backend/./app.py 89
2024-10-20 16:28:08,722 INFO App created successfully: /home/frank/eazy_manage_backend/./app.py 99
2024-10-20 17:00:19,940 INFO Logging setup successfully: /home/frank/eazy_manage_backend/./app.py 43
2024-10-20 17:00:20,060 INFO DataBase set up successfully: /home/frank/eazy_manage_backend/./app.py 55
2024-10-20 17:00:30,290 INFO database set up successfully: /home/frank/eazy_manage_backend/./app.py 60
2024-10-20 17:00:30,657 INFO Migrations set up successfully: /home/frank/eazy_manage_backend/./app.py 68
2024-10-20 17:00:30,704 INFO Blueprints registered successfully: /home/frank/eazy_manage_backend/./app.py 76
2024-10-20 17:00:30,706 INFO Mail service setup successfully: /home/frank/eazy_manage_backend/./app.py 89
2024-10-20 17:00:30,707 INFO App created successfully: /home/frank/eazy_manage_backend/./app.py 99
2024-10-20 17:00:39,173 INFO Logging setup successfully: /home/frank/eazy_manage_backend/./app.py 43
2024-10-20 17:00:39,174 INFO DataBase set up successfully: /home/frank/eazy_manage_backend/./app.py 55
2024-10-20 17:00:39,374 INFO database set up successfully: /home/frank/eazy_manage_backend/./app.py 60
2024-10-20 17:00:39,387 INFO Migrations set up successfully: /home/frank/eazy_manage_backend/./app.py 68
2024-10-20 17:00:39,419 INFO Blueprints registered successfully: /home/frank/eazy_manage_backend/./app.py 76
2024-10-20 17:00:39,420 INFO Mail service setup successfully: /home/frank/eazy_manage_backend/./app.py 89
2024-10-20 17:00:39,421 INFO App created successfully: /home/frank/eazy_manage_backend/./app.py 99
2024-10-20 17:01:35,552 WARNING Error fetching tasks: /home/frank/eazy_manage_backend/api/v1/routes/employees.py 36
Traceback (most recent call last):
  File "/home/frank/eazy_manage_backend/api/v1/routes/employees.py", line 34, in get_tasks
    serialized_data = [task.to_dict() for task in tasks]
  File "/home/frank/eazy_manage_backend/api/v1/routes/employees.py", line 34, in <listcomp>
    serialized_data = [task.to_dict() for task in tasks]
  File "/home/frank/eazy_manage_backend/models/models.py", line 66, in to_dict
    'team': self.team,
AttributeError: 'Tasks' object has no attribute 'team'
2024-10-20 17:02:45,331 INFO Logging setup successfully: /home/frank/eazy_manage_backend/./app.py 43
2024-10-20 17:02:45,333 INFO DataBase set up successfully: /home/frank/eazy_manage_backend/./app.py 55
2024-10-20 17:02:45,548 INFO database set up successfully: /home/frank/eazy_manage_backend/./app.py 60
2024-10-20 17:02:45,562 INFO Migrations set up successfully: /home/frank/eazy_manage_backend/./app.py 68
2024-10-20 17:02:45,595 INFO Blueprints registered successfully: /home/frank/eazy_manage_backend/./app.py 76
2024-10-20 17:02:45,597 INFO Mail service setup successfully: /home/frank/eazy_manage_backend/./app.py 89
2024-10-20 17:02:45,598 INFO App created successfully: /home/frank/eazy_manage_backend/./app.py 99
2024-10-20 17:03:39,585 INFO Logging setup successfully: /home/frank/eazy_manage_backend/app.py 43
2024-10-20 17:03:39,586 INFO DataBase set up successfully: /home/frank/eazy_manage_backend/app.py 55
2024-10-20 17:03:39,747 INFO database set up successfully: /home/frank/eazy_manage_backend/app.py 60
2024-10-20 17:03:39,756 INFO Migrations set up successfully: /home/frank/eazy_manage_backend/app.py 68
2024-10-20 17:03:39,781 INFO Blueprints registered successfully: /home/frank/eazy_manage_backend/app.py 76
2024-10-20 17:03:39,782 INFO Mail service setup successfully: /home/frank/eazy_manage_backend/app.py 89
2024-10-20 17:03:39,782 INFO App created successfully: /home/frank/eazy_manage_backend/app.py 99
2024-10-20 17:03:50,670 INFO Logging setup successfully: /home/frank/eazy_manage_backend/app.py 43
2024-10-20 17:03:50,671 INFO DataBase set up successfully: /home/frank/eazy_manage_backend/app.py 55
2024-10-20 17:03:50,826 INFO database set up successfully: /home/frank/eazy_manage_backend/app.py 60
2024-10-20 17:03:50,839 INFO Migrations set up successfully: /home/frank/eazy_manage_backend/app.py 68
2024-10-20 17:03:50,869 INFO Blueprints registered successfully: /home/frank/eazy_manage_backend/app.py 76
2024-10-20 17:03:50,870 INFO Mail service setup successfully: /home/frank/eazy_manage_backend/app.py 89
2024-10-20 17:03:50,871 INFO App created successfully: /home/frank/eazy_manage_backend/app.py 99
2024-10-20 17:04:10,106 INFO Logging setup successfully: /home/frank/eazy_manage_backend/app.py 43
2024-10-20 17:04:10,107 INFO DataBase set up successfully: /home/frank/eazy_manage_backend/app.py 55
2024-10-20 17:04:10,283 INFO database set up successfully: /home/frank/eazy_manage_backend/app.py 60
2024-10-20 17:04:10,295 INFO Migrations set up successfully: /home/frank/eazy_manage_backend/app.py 68
2024-10-20 17:04:10,322 INFO Blueprints registered successfully: /home/frank/eazy_manage_backend/app.py 76
2024-10-20 17:04:10,323 INFO Mail service setup successfully: /home/frank/eazy_manage_backend/app.py 89
2024-10-20 17:04:10,324 INFO App created successfully: /home/frank/eazy_manage_backend/app.py 99
2024-10-20 17:08:46,735 INFO Logging setup successfully: /home/frank/eazy_manage_backend/./app.py 43
2024-10-20 17:08:46,736 INFO DataBase set up successfully: /home/frank/eazy_manage_backend/./app.py 55
2024-10-20 17:08:46,947 INFO database set up successfully: /home/frank/eazy_manage_backend/./app.py 60
2024-10-20 17:08:46,960 INFO Migrations set up successfully: /home/frank/eazy_manage_backend/./app.py 68
2024-10-20 17:08:46,989 INFO Blueprints registered successfully: /home/frank/eazy_manage_backend/./app.py 76
2024-10-20 17:08:46,990 INFO Mail service setup successfully: /home/frank/eazy_manage_backend/./app.py 89
2024-10-20 17:08:46,991 INFO App created successfully: /home/frank/eazy_manage_backend/./app.py 99
2024-10-20 17:08:57,555 WARNING Error fetching tasks: /home/frank/eazy_manage_backend/api/v1/routes/employees.py 37
Traceback (most recent call last):
  File "/home/frank/eazy_manage_backend/api/v1/routes/employees.py", line 35, in get_tasks
    serialized_data = [task.to_dict() for task in tasks]
  File "/home/frank/eazy_manage_backend/api/v1/routes/employees.py", line 35, in <listcomp>
    serialized_data = [task.to_dict() for task in tasks]
  File "/home/frank/eazy_manage_backend/models/models.py", line 69, in to_dict
    'planned_end_date': self.planned_end_date.strftime('%Y-%m-%d') if self.planned_end_date else None,  # Format date
AttributeError: 'Tasks' object has no attribute 'planned_end_date'
2024-10-20 17:11:27,621 INFO Logging setup successfully: /home/frank/eazy_manage_backend/./app.py 43
2024-10-20 17:11:27,622 INFO DataBase set up successfully: /home/frank/eazy_manage_backend/./app.py 55
2024-10-20 17:11:27,787 INFO database set up successfully: /home/frank/eazy_manage_backend/./app.py 60
2024-10-20 17:11:27,799 INFO Migrations set up successfully: /home/frank/eazy_manage_backend/./app.py 68
2024-10-20 17:11:27,832 INFO Blueprints registered successfully: /home/frank/eazy_manage_backend/./app.py 76
2024-10-20 17:11:27,833 INFO Mail service setup successfully: /home/frank/eazy_manage_backend/./app.py 89
2024-10-20 17:11:27,834 INFO App created successfully: /home/frank/eazy_manage_backend/./app.py 99
2024-10-20 17:16:30,979 INFO Logging setup successfully: /home/frank/eazy_manage_backend/./app.py 43
2024-10-20 17:16:30,980 INFO DataBase set up successfully: /home/frank/eazy_manage_backend/./app.py 55
2024-10-20 17:16:31,164 INFO database set up successfully: /home/frank/eazy_manage_backend/./app.py 60
2024-10-20 17:16:31,179 INFO Migrations set up successfully: /home/frank/eazy_manage_backend/./app.py 68
2024-10-20 17:16:31,206 INFO Blueprints registered successfully: /home/frank/eazy_manage_backend/./app.py 76
2024-10-20 17:16:31,207 INFO Mail service setup successfully: /home/frank/eazy_manage_backend/./app.py 89
2024-10-20 17:16:31,208 INFO App created successfully: /home/frank/eazy_manage_backend/./app.py 99
2024-10-20 19:05:41,125 INFO Logging setup successfully: /home/frank/eazy_manage_backend/./app.py 43
2024-10-20 19:05:41,126 INFO DataBase set up successfully: /home/frank/eazy_manage_backend/./app.py 55
2024-10-20 19:05:41,235 INFO database set up successfully: /home/frank/eazy_manage_backend/./app.py 60
2024-10-20 19:05:41,241 INFO Migrations set up successfully: /home/frank/eazy_manage_backend/./app.py 68
2024-10-20 19:05:41,257 INFO Blueprints registered successfully: /home/frank/eazy_manage_backend/./app.py 76
2024-10-20 19:05:41,257 INFO Mail service setup successfully: /home/frank/eazy_manage_backend/./app.py 89
2024-10-20 19:05:41,258 INFO App created successfully: /home/frank/eazy_manage_backend/./app.py 99
2024-10-20 19:05:44,462 INFO Logging setup successfully: /home/frank/eazy_manage_backend/./app.py 43
2024-10-20 19:05:44,464 INFO DataBase set up successfully: /home/frank/eazy_manage_backend/./app.py 55
2024-10-20 19:05:44,777 INFO database set up successfully: /home/frank/eazy_manage_backend/./app.py 60
2024-10-20 19:05:44,795 INFO Migrations set up successfully: /home/frank/eazy_manage_backend/./app.py 68
2024-10-20 19:05:44,834 INFO Blueprints registered successfully: /home/frank/eazy_manage_backend/./app.py 76
2024-10-20 19:05:44,835 INFO Mail service setup successfully: /home/frank/eazy_manage_backend/./app.py 89
2024-10-20 19:05:44,836 INFO App created successfully: /home/frank/eazy_manage_backend/./app.py 99
2024-10-20 19:40:24,928 INFO Logging setup successfully: /home/frank/eazy_manage_backend/./app.py 43
2024-10-20 19:40:24,944 INFO DataBase set up successfully: /home/frank/eazy_manage_backend/./app.py 55
2024-10-20 19:40:25,138 INFO database set up successfully: /home/frank/eazy_manage_backend/./app.py 60
2024-10-20 19:40:25,148 INFO Migrations set up successfully: /home/frank/eazy_manage_backend/./app.py 68
2024-10-20 19:40:25,173 INFO Blueprints registered successfully: /home/frank/eazy_manage_backend/./app.py 76
2024-10-20 19:40:25,174 INFO Mail service setup successfully: /home/frank/eazy_manage_backend/./app.py 89
2024-10-20 19:40:25,175 INFO App created successfully: /home/frank/eazy_manage_backend/./app.py 99
2024-10-20 22:32:00,016 INFO Logging setup successfully: /home/frank/eazy_manage_backend/./app.py 43
2024-10-20 22:32:00,016 INFO DataBase set up successfully: /home/frank/eazy_manage_backend/./app.py 55
2024-10-20 22:32:00,212 INFO database set up successfully: /home/frank/eazy_manage_backend/./app.py 60
2024-10-20 22:32:00,222 INFO Migrations set up successfully: /home/frank/eazy_manage_backend/./app.py 68
2024-10-20 22:32:00,245 INFO Blueprints registered successfully: /home/frank/eazy_manage_backend/./app.py 76
2024-10-20 22:32:00,246 INFO Mail service setup successfully: /home/frank/eazy_manage_backend/./app.py 89
2024-10-20 22:32:00,247 INFO App created successfully: /home/frank/eazy_manage_backend/./app.py 99
2024-10-20 22:32:03,168 INFO Logging setup successfully: /home/frank/eazy_manage_backend/./app.py 43
2024-10-20 22:32:03,169 INFO DataBase set up successfully: /home/frank/eazy_manage_backend/./app.py 55
2024-10-20 22:32:03,329 INFO database set up successfully: /home/frank/eazy_manage_backend/./app.py 60
2024-10-20 22:32:03,343 INFO Migrations set up successfully: /home/frank/eazy_manage_backend/./app.py 68
2024-10-20 22:32:03,385 INFO Blueprints registered successfully: /home/frank/eazy_manage_backend/./app.py 76
2024-10-20 22:32:03,387 INFO Mail service setup successfully: /home/frank/eazy_manage_backend/./app.py 89
2024-10-20 22:32:03,388 INFO App created successfully: /home/frank/eazy_manage_backend/./app.py 99
2024-10-20 22:32:22,246 INFO Logging setup successfully: /home/frank/eazy_manage_backend/./app.py 43
2024-10-20 22:32:22,247 INFO DataBase set up successfully: /home/frank/eazy_manage_backend/./app.py 55
2024-10-20 22:32:22,331 INFO database set up successfully: /home/frank/eazy_manage_backend/./app.py 60
2024-10-20 22:32:22,336 INFO Migrations set up successfully: /home/frank/eazy_manage_backend/./app.py 68
2024-10-20 22:32:22,349 INFO Blueprints registered successfully: /home/frank/eazy_manage_backend/./app.py 76
2024-10-20 22:32:22,349 INFO Mail service setup successfully: /home/frank/eazy_manage_backend/./app.py 89
2024-10-20 22:32:22,349 INFO App created successfully: /home/frank/eazy_manage_backend/./app.py 99
2024-10-20 22:32:43,851 INFO Logging setup successfully: /home/frank/eazy_manage_backend/./app.py 43
2024-10-20 22:32:43,852 INFO DataBase set up successfully: /home/frank/eazy_manage_backend/./app.py 55
2024-10-20 22:32:44,063 INFO database set up successfully: /home/frank/eazy_manage_backend/./app.py 60
2024-10-20 22:32:44,079 INFO Migrations set up successfully: /home/frank/eazy_manage_backend/./app.py 68
2024-10-20 22:32:44,104 INFO Blueprints registered successfully: /home/frank/eazy_manage_backend/./app.py 76
2024-10-20 22:32:44,105 INFO Mail service setup successfully: /home/frank/eazy_manage_backend/./app.py 89
2024-10-20 22:32:44,105 INFO App created successfully: /home/frank/eazy_manage_backend/./app.py 99
2024-10-20 23:51:41,295 ERROR Task status update failed: /home/frank/eazy_manage_backend/api/v1/routes/employees.py 106
Traceback (most recent call last):
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1970, in _exec_single_context
    self.dialect.do_execute(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1265, "Data truncated for column 'status' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/frank/eazy_manage_backend/api/v1/routes/employees.py", line 103, in change_task_status
    db.session.commit()
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4296, in flush
    self._flush(objects)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4431, in _flush
    with util.safe_reraise():
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4392, in _flush
    flush_context.execute()
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 85, in save_obj
    _emit_update_statements(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 912, in _emit_update_statements
    c = connection.execute(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1421, in execute
    return meth(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1643, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1849, in _execute_context
    return self._exec_single_context(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1989, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2356, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1970, in _exec_single_context
    self.dialect.do_execute(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.DataError: (pymysql.err.DataError) (1265, "Data truncated for column 'status' at row 1")
[SQL: UPDATE tasks SET status=%(status)s WHERE tasks.task_id = %(tasks_task_id)s]
[parameters: {'status': 'completed', 'tasks_task_id': '9645c437-449a-4372-b415-1fff87e1bcc2'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
2024-10-20 23:51:49,428 ERROR Task status update failed: /home/frank/eazy_manage_backend/api/v1/routes/employees.py 106
Traceback (most recent call last):
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1970, in _exec_single_context
    self.dialect.do_execute(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1265, "Data truncated for column 'status' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/frank/eazy_manage_backend/api/v1/routes/employees.py", line 103, in change_task_status
    db.session.commit()
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4296, in flush
    self._flush(objects)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4431, in _flush
    with util.safe_reraise():
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4392, in _flush
    flush_context.execute()
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 85, in save_obj
    _emit_update_statements(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 912, in _emit_update_statements
    c = connection.execute(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1421, in execute
    return meth(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1643, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1849, in _execute_context
    return self._exec_single_context(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1989, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2356, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1970, in _exec_single_context
    self.dialect.do_execute(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.DataError: (pymysql.err.DataError) (1265, "Data truncated for column 'status' at row 1")
[SQL: UPDATE tasks SET status=%(status)s WHERE tasks.task_id = %(tasks_task_id)s]
[parameters: {'status': 'completed', 'tasks_task_id': '96110f2c-2431-4f40-9777-ce9b9c11344e'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
2024-10-20 23:53:39,750 INFO Logging setup successfully: /home/frank/eazy_manage_backend/./app.py 43
2024-10-20 23:53:39,751 INFO DataBase set up successfully: /home/frank/eazy_manage_backend/./app.py 55
2024-10-20 23:53:39,793 INFO database set up successfully: /home/frank/eazy_manage_backend/./app.py 60
2024-10-20 23:53:39,796 INFO Migrations set up successfully: /home/frank/eazy_manage_backend/./app.py 68
2024-10-20 23:53:39,802 INFO Blueprints registered successfully: /home/frank/eazy_manage_backend/./app.py 76
2024-10-20 23:53:39,802 INFO Mail service setup successfully: /home/frank/eazy_manage_backend/./app.py 89
2024-10-20 23:53:39,803 INFO App created successfully: /home/frank/eazy_manage_backend/./app.py 99
2024-10-20 23:54:15,036 INFO Logging setup successfully: /home/frank/eazy_manage_backend/app.py 43
2024-10-20 23:54:15,036 INFO DataBase set up successfully: /home/frank/eazy_manage_backend/app.py 55
2024-10-20 23:54:15,081 INFO database set up successfully: /home/frank/eazy_manage_backend/app.py 60
2024-10-20 23:54:15,084 INFO Migrations set up successfully: /home/frank/eazy_manage_backend/app.py 68
2024-10-20 23:54:15,090 INFO Blueprints registered successfully: /home/frank/eazy_manage_backend/app.py 76
2024-10-20 23:54:15,090 INFO Mail service setup successfully: /home/frank/eazy_manage_backend/app.py 89
2024-10-20 23:54:15,091 INFO App created successfully: /home/frank/eazy_manage_backend/app.py 99
2024-10-20 23:54:28,310 INFO Logging setup successfully: /home/frank/eazy_manage_backend/app.py 43
2024-10-20 23:54:28,310 INFO DataBase set up successfully: /home/frank/eazy_manage_backend/app.py 55
2024-10-20 23:54:28,352 INFO database set up successfully: /home/frank/eazy_manage_backend/app.py 60
2024-10-20 23:54:28,355 INFO Migrations set up successfully: /home/frank/eazy_manage_backend/app.py 68
2024-10-20 23:54:28,361 INFO Blueprints registered successfully: /home/frank/eazy_manage_backend/app.py 76
2024-10-20 23:54:28,361 INFO Mail service setup successfully: /home/frank/eazy_manage_backend/app.py 89
2024-10-20 23:54:28,361 INFO App created successfully: /home/frank/eazy_manage_backend/app.py 99
