2024-10-23 20:35:05,861 WARNING Error fetching tasks: /home/frank/eazy_manage_backend/api/v1/routes/tasks.py 62
Traceback (most recent call last):
  File "/home/frank/eazy_manage_backend/api/v1/routes/tasks.py", line 43, in get_tasks
    and_(Tasks.ended >= from_date, Tasks.ended <= to_date)) if filter else None)\
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/sql/operators.py", line 637, in __ge__
    return self.operate(ge, other)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 453, in operate
    return op(self.comparator, *other, **kwargs)  # type: ignore[no-any-return]  # noqa: E501
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/sql/operators.py", line 637, in __ge__
    return self.operate(ge, other)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/properties.py", line 478, in operate
    return op(self.__clause_element__(), *other, **kwargs)  # type: ignore[no-any-return]  # noqa: E501
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/sql/operators.py", line 637, in __ge__
    return self.operate(ge, other)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 1511, in operate
    return op(self.comparator, *other, **kwargs)  # type: ignore[no-any-return]  # noqa: E501
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/sql/operators.py", line 637, in __ge__
    return self.operate(ge, other)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/sql/type_api.py", line 194, in operate
    return op_fn(self.expr, op, *other, **addtl_kw)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/sql/default_comparator.py", line 115, in _boolean_compare
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Only '=', '!=', 'is_()', 'is_not()', 'is_distinct_from()', 'is_not_distinct_from()' operators can be used with None/True/False
2024-10-23 20:35:59,941 INFO Logging setup successfully: /home/frank/eazy_manage_backend/./app.py 43
2024-10-23 20:35:59,943 INFO DataBase set up successfully: /home/frank/eazy_manage_backend/./app.py 55
2024-10-23 20:36:00,200 INFO database set up successfully: /home/frank/eazy_manage_backend/./app.py 60
2024-10-23 20:36:00,206 INFO Migrations set up successfully: /home/frank/eazy_manage_backend/./app.py 68
2024-10-23 20:36:00,220 INFO Blueprints registered successfully: /home/frank/eazy_manage_backend/./app.py 76
2024-10-23 20:36:00,220 INFO Mail service setup successfully: /home/frank/eazy_manage_backend/./app.py 89
2024-10-23 20:36:00,221 INFO App created successfully: /home/frank/eazy_manage_backend/./app.py 99
2024-10-23 20:36:01,327 WARNING Error fetching tasks: /home/frank/eazy_manage_backend/api/v1/routes/tasks.py 62
Traceback (most recent call last):
  File "/home/frank/eazy_manage_backend/api/v1/routes/tasks.py", line 41, in get_tasks
    (and_(Tasks.started >= from_date, Tasks.started <= to_date)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/sql/operators.py", line 637, in __ge__
    return self.operate(ge, other)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 453, in operate
    return op(self.comparator, *other, **kwargs)  # type: ignore[no-any-return]  # noqa: E501
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/sql/operators.py", line 637, in __ge__
    return self.operate(ge, other)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/properties.py", line 478, in operate
    return op(self.__clause_element__(), *other, **kwargs)  # type: ignore[no-any-return]  # noqa: E501
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/sql/operators.py", line 637, in __ge__
    return self.operate(ge, other)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 1511, in operate
    return op(self.comparator, *other, **kwargs)  # type: ignore[no-any-return]  # noqa: E501
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/sql/operators.py", line 637, in __ge__
    return self.operate(ge, other)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/sql/type_api.py", line 194, in operate
    return op_fn(self.expr, op, *other, **addtl_kw)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/sql/default_comparator.py", line 115, in _boolean_compare
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Only '=', '!=', 'is_()', 'is_not()', 'is_distinct_from()', 'is_not_distinct_from()' operators can be used with None/True/False
2024-10-23 20:36:56,743 INFO Logging setup successfully: /home/frank/eazy_manage_backend/./app.py 43
2024-10-23 20:36:56,744 INFO DataBase set up successfully: /home/frank/eazy_manage_backend/./app.py 55
2024-10-23 20:36:56,865 INFO database set up successfully: /home/frank/eazy_manage_backend/./app.py 60
2024-10-23 20:36:56,870 INFO Migrations set up successfully: /home/frank/eazy_manage_backend/./app.py 68
2024-10-23 20:36:56,890 INFO Blueprints registered successfully: /home/frank/eazy_manage_backend/./app.py 76
2024-10-23 20:36:56,891 INFO Mail service setup successfully: /home/frank/eazy_manage_backend/./app.py 89
2024-10-23 20:36:56,891 INFO App created successfully: /home/frank/eazy_manage_backend/./app.py 99
2024-10-23 20:36:57,957 WARNING Error fetching tasks: /home/frank/eazy_manage_backend/api/v1/routes/tasks.py 63
Traceback (most recent call last):
  File "/home/frank/eazy_manage_backend/api/v1/routes/tasks.py", line 44, in get_tasks
    and_(Tasks.ended >= from_date, Tasks.ended <= to_date)) if filter else None)\
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/sql/operators.py", line 637, in __ge__
    return self.operate(ge, other)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 453, in operate
    return op(self.comparator, *other, **kwargs)  # type: ignore[no-any-return]  # noqa: E501
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/sql/operators.py", line 637, in __ge__
    return self.operate(ge, other)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/properties.py", line 478, in operate
    return op(self.__clause_element__(), *other, **kwargs)  # type: ignore[no-any-return]  # noqa: E501
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/sql/operators.py", line 637, in __ge__
    return self.operate(ge, other)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 1511, in operate
    return op(self.comparator, *other, **kwargs)  # type: ignore[no-any-return]  # noqa: E501
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/sql/operators.py", line 637, in __ge__
    return self.operate(ge, other)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/sql/type_api.py", line 194, in operate
    return op_fn(self.expr, op, *other, **addtl_kw)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/sql/default_comparator.py", line 115, in _boolean_compare
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Only '=', '!=', 'is_()', 'is_not()', 'is_distinct_from()', 'is_not_distinct_from()' operators can be used with None/True/False
2024-10-23 20:40:21,312 INFO Logging setup successfully: /home/frank/eazy_manage_backend/./app.py 43
2024-10-23 20:40:21,313 INFO DataBase set up successfully: /home/frank/eazy_manage_backend/./app.py 55
2024-10-23 20:40:21,506 INFO database set up successfully: /home/frank/eazy_manage_backend/./app.py 60
2024-10-23 20:40:21,526 INFO Migrations set up successfully: /home/frank/eazy_manage_backend/./app.py 68
2024-10-23 20:40:21,564 INFO Blueprints registered successfully: /home/frank/eazy_manage_backend/./app.py 76
2024-10-23 20:40:21,566 INFO Mail service setup successfully: /home/frank/eazy_manage_backend/./app.py 89
2024-10-23 20:40:21,567 INFO App created successfully: /home/frank/eazy_manage_backend/./app.py 99
2024-10-23 21:11:45,480 INFO Logging setup successfully: /home/frank/eazy_manage_backend/./app.py 43
2024-10-23 21:11:45,481 INFO DataBase set up successfully: /home/frank/eazy_manage_backend/./app.py 55
2024-10-23 21:11:45,984 INFO database set up successfully: /home/frank/eazy_manage_backend/./app.py 60
2024-10-23 21:11:45,990 INFO Migrations set up successfully: /home/frank/eazy_manage_backend/./app.py 68
2024-10-23 21:11:46,006 INFO Blueprints registered successfully: /home/frank/eazy_manage_backend/./app.py 76
2024-10-23 21:11:46,007 INFO Mail service setup successfully: /home/frank/eazy_manage_backend/./app.py 89
2024-10-23 21:11:46,007 INFO App created successfully: /home/frank/eazy_manage_backend/./app.py 99
2024-10-23 21:11:47,989 INFO Logging setup successfully: /home/frank/eazy_manage_backend/./app.py 43
2024-10-23 21:11:47,990 INFO DataBase set up successfully: /home/frank/eazy_manage_backend/./app.py 55
2024-10-23 21:11:48,100 INFO database set up successfully: /home/frank/eazy_manage_backend/./app.py 60
2024-10-23 21:11:48,106 INFO Migrations set up successfully: /home/frank/eazy_manage_backend/./app.py 68
2024-10-23 21:11:48,118 INFO Blueprints registered successfully: /home/frank/eazy_manage_backend/./app.py 76
2024-10-23 21:11:48,119 INFO Mail service setup successfully: /home/frank/eazy_manage_backend/./app.py 89
2024-10-23 21:11:48,119 INFO App created successfully: /home/frank/eazy_manage_backend/./app.py 99
2024-10-23 21:38:38,279 INFO Logging setup successfully: /home/frank/eazy_manage_backend/app.py 43
2024-10-23 21:38:38,280 INFO DataBase set up successfully: /home/frank/eazy_manage_backend/app.py 55
2024-10-23 21:38:38,820 INFO database set up successfully: /home/frank/eazy_manage_backend/app.py 60
2024-10-23 21:38:38,821 INFO Migrations set up successfully: /home/frank/eazy_manage_backend/app.py 68
2024-10-23 21:38:38,966 INFO Blueprints registered successfully: /home/frank/eazy_manage_backend/app.py 76
2024-10-23 21:38:38,967 INFO Mail service setup successfully: /home/frank/eazy_manage_backend/app.py 89
2024-10-23 21:38:38,967 INFO App created successfully: /home/frank/eazy_manage_backend/app.py 99
2024-10-23 23:55:10,793 INFO Logging setup successfully: /home/frank/eazy_manage_backend/./app.py 43
2024-10-23 23:55:10,794 INFO DataBase set up successfully: /home/frank/eazy_manage_backend/./app.py 55
2024-10-23 23:55:10,955 INFO database set up successfully: /home/frank/eazy_manage_backend/./app.py 60
2024-10-23 23:55:10,958 INFO Migrations set up successfully: /home/frank/eazy_manage_backend/./app.py 68
2024-10-23 23:55:10,964 INFO Blueprints registered successfully: /home/frank/eazy_manage_backend/./app.py 76
2024-10-23 23:55:10,964 INFO Mail service setup successfully: /home/frank/eazy_manage_backend/./app.py 89
2024-10-23 23:55:10,964 INFO App created successfully: /home/frank/eazy_manage_backend/./app.py 99
2024-10-23 23:55:27,196 WARNING Error fetching tasks: /home/frank/eazy_manage_backend/api/v1/routes/tasks.py 58
Traceback (most recent call last):
  File "/home/frank/eazy_manage_backend/api/v1/routes/tasks.py", line 50, in get_tasks
    tasks = query.order_by(Tasks.started.desc()) if status == 'pending' else query.order_by(Tasks.ended.desc()).all()
  File "<string>", line 2, in order_by
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/sql/base.py", line 280, in _generative
    x = fn(self, *args, **kw)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2027, in order_by
    assertion("order_by")
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 442, in _no_limit_offset
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Query.order_by() being called on a Query which already has LIMIT or OFFSET applied.  Call order_by() before limit() or offset() are applied.
2024-10-23 23:55:44,305 WARNING Error fetching tasks: /home/frank/eazy_manage_backend/api/v1/routes/tasks.py 58
Traceback (most recent call last):
  File "/home/frank/eazy_manage_backend/api/v1/routes/tasks.py", line 50, in get_tasks
    tasks = query.order_by(Tasks.started.desc()) if status == 'pending' else query.order_by(Tasks.ended.desc()).all()
  File "<string>", line 2, in order_by
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/sql/base.py", line 280, in _generative
    x = fn(self, *args, **kw)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2027, in order_by
    assertion("order_by")
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 442, in _no_limit_offset
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Query.order_by() being called on a Query which already has LIMIT or OFFSET applied.  Call order_by() before limit() or offset() are applied.
2024-10-23 23:57:18,051 INFO Logging setup successfully: /home/frank/eazy_manage_backend/./app.py 43
2024-10-23 23:57:18,051 INFO DataBase set up successfully: /home/frank/eazy_manage_backend/./app.py 55
2024-10-23 23:57:18,145 INFO database set up successfully: /home/frank/eazy_manage_backend/./app.py 60
2024-10-23 23:57:18,149 INFO Migrations set up successfully: /home/frank/eazy_manage_backend/./app.py 68
2024-10-23 23:57:18,155 INFO Blueprints registered successfully: /home/frank/eazy_manage_backend/./app.py 76
2024-10-23 23:57:18,156 INFO Mail service setup successfully: /home/frank/eazy_manage_backend/./app.py 89
2024-10-23 23:57:18,156 INFO App created successfully: /home/frank/eazy_manage_backend/./app.py 99
2024-10-24 00:46:25,835 INFO Logging setup successfully: /home/frank/eazy_manage_backend/./app.py 43
2024-10-24 00:46:25,835 INFO DataBase set up successfully: /home/frank/eazy_manage_backend/./app.py 55
2024-10-24 00:46:25,932 INFO database set up successfully: /home/frank/eazy_manage_backend/./app.py 60
2024-10-24 00:46:25,935 INFO Migrations set up successfully: /home/frank/eazy_manage_backend/./app.py 68
2024-10-24 00:46:25,942 INFO Blueprints registered successfully: /home/frank/eazy_manage_backend/./app.py 76
2024-10-24 00:46:25,943 INFO Mail service setup successfully: /home/frank/eazy_manage_backend/./app.py 89
2024-10-24 00:46:25,943 INFO App created successfully: /home/frank/eazy_manage_backend/./app.py 99
2024-10-24 00:47:25,331 WARNING Error fetching tasks: /home/frank/eazy_manage_backend/api/v1/routes/tasks.py 58
Traceback (most recent call last):
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1970, in _exec_single_context
    self.dialect.do_execute(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1241, 'Operand should contain 1 column(s)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/frank/eazy_manage_backend/api/v1/routes/tasks.py", line 50, in get_tasks
    tasks = query.offset(offset).limit(limit).all()
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2673, in all
    return self._iter().all()  # type: ignore
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2827, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2306, in execute
    return self._execute_internal(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2191, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1421, in execute
    return meth(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1643, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1849, in _execute_context
    return self._exec_single_context(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1989, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2356, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1970, in _exec_single_context
    self.dialect.do_execute(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1241, 'Operand should contain 1 column(s)')
[SQL: SELECT count(*) OVER () AS total, tasks.task_id AS tasks_task_id, tasks.task_name AS tasks_task_name, tasks.description AS tasks_description, tasks.started AS tasks_started, tasks.to_end AS tasks_to_end, tasks.ended AS tasks_ended, tasks.priority AS tasks_priority, tasks.status AS tasks_status, tasks.notes AS tasks_notes, tasks.comments AS tasks_comments, tasks.user_id AS tasks_user_id 
FROM tasks 
WHERE tasks.user_id = %(user_id_1)s AND tasks.status = %(status_1)s AND (SELECT count(*) OVER () AS total, tasks.task_id, tasks.task_name, tasks.description, tasks.started, tasks.to_end, tasks.ended, tasks.priority, tasks.status, tasks.notes, tasks.comments, tasks.user_id 
FROM tasks 
WHERE tasks.user_id = %(user_id_1)s AND tasks.status = %(status_1)s AND tasks.ended >= %(ended_1)s AND tasks.ended <= %(ended_2)s) ORDER BY tasks.ended DESC 
 LIMIT %(param_1)s, %(param_2)s]
[parameters: {'user_id_1': '62a22a67-ee78-422e-b456-26d8a5963861', 'status_1': 'completed', 'ended_1': '2024-10-30', 'ended_2': '2024-10-31', 'param_1': 0, 'param_2': 20}]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-10-24 00:48:19,688 WARNING Error fetching tasks: /home/frank/eazy_manage_backend/api/v1/routes/tasks.py 58
Traceback (most recent call last):
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1970, in _exec_single_context
    self.dialect.do_execute(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1241, 'Operand should contain 1 column(s)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/frank/eazy_manage_backend/api/v1/routes/tasks.py", line 50, in get_tasks
    tasks = query.offset(offset).limit(limit).all()
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2673, in all
    return self._iter().all()  # type: ignore
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2827, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2306, in execute
    return self._execute_internal(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2191, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1421, in execute
    return meth(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1643, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1849, in _execute_context
    return self._exec_single_context(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1989, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2356, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1970, in _exec_single_context
    self.dialect.do_execute(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1241, 'Operand should contain 1 column(s)')
[SQL: SELECT count(*) OVER () AS total, tasks.task_id AS tasks_task_id, tasks.task_name AS tasks_task_name, tasks.description AS tasks_description, tasks.started AS tasks_started, tasks.to_end AS tasks_to_end, tasks.ended AS tasks_ended, tasks.priority AS tasks_priority, tasks.status AS tasks_status, tasks.notes AS tasks_notes, tasks.comments AS tasks_comments, tasks.user_id AS tasks_user_id 
FROM tasks 
WHERE tasks.user_id = %(user_id_1)s AND tasks.status = %(status_1)s AND (SELECT count(*) OVER () AS total, tasks.task_id, tasks.task_name, tasks.description, tasks.started, tasks.to_end, tasks.ended, tasks.priority, tasks.status, tasks.notes, tasks.comments, tasks.user_id 
FROM tasks 
WHERE tasks.user_id = %(user_id_1)s AND tasks.status = %(status_1)s AND tasks.ended >= %(ended_1)s AND tasks.ended <= %(ended_2)s) ORDER BY tasks.ended DESC 
 LIMIT %(param_1)s, %(param_2)s]
[parameters: {'user_id_1': '62a22a67-ee78-422e-b456-26d8a5963861', 'status_1': 'completed', 'ended_1': '2024-10-25', 'ended_2': '2024-10-30', 'param_1': 0, 'param_2': 20}]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
