2024-08-14 00:19:20,814 ERROR pharmacy registration failed: /home/frank/virtual_doctor_backend/api/auth.py 101
Traceback (most recent call last):
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1970, in _exec_single_context
    self.dialect.do_execute(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1265, "Data truncated for column 'verification' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/frank/virtual_doctor_backend/api/auth.py", line 98, in register
    db.session.commit()
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4296, in flush
    self._flush(objects)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4431, in _flush
    with util.safe_reraise():
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4392, in _flush
    flush_context.execute()
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1421, in execute
    return meth(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1643, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1849, in _execute_context
    return self._exec_single_context(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1989, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2356, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1970, in _exec_single_context
    self.dialect.do_execute(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.DataError: (pymysql.err.DataError) (1265, "Data truncated for column 'verification' at row 1")
[SQL: INSERT INTO pharmacy (pharm_uuid, pharm_name, pharm_address, contact, email, password, verification, reg_date, hosp_id) VALUES (%(pharm_uuid)s, %(pharm_name)s, %(pharm_address)s, %(contact)s, %(email)s, %(password)s, %(verification)s, %(reg_date)s, %(hosp_id)s)]
[parameters: {'pharm_uuid': 'dc424458-038d-4c5f-84b1-c1b47acff2e0', 'pharm_name': 'Francis Chege', 'pharm_address': 'Ngong, Kajiado, Kenya', 'contact': '0712750179', 'email': 'francischege602@gmail.com', 'password': b'$2b$12$eH3z4SjiaxRbDQuETQ8qE.iYblnQHDjlaG4YtWbHe51bcdhb1gE3.', 'verification': 'unverified', 'reg_date': None, 'hosp_id': None}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
2024-08-14 00:24:25,134 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 32
2024-08-14 00:24:25,135 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 50
NoneType: None
2024-08-14 00:24:25,135 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 62
2024-08-14 00:24:25,215 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 74
2024-08-14 00:24:25,234 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 82
2024-08-14 00:24:25,234 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 95
2024-08-14 00:24:25,234 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 105
2024-08-14 00:24:59,548 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/app.py 32
2024-08-14 00:24:59,549 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/app.py 50
NoneType: None
2024-08-14 00:24:59,549 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/app.py 62
2024-08-14 00:24:59,611 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/app.py 74
2024-08-14 00:24:59,661 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/app.py 82
2024-08-14 00:24:59,661 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/app.py 95
2024-08-14 00:24:59,661 INFO App created successfully: /home/frank/virtual_doctor_backend/app.py 105
2024-08-14 00:25:09,677 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/app.py 32
2024-08-14 00:25:09,678 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/app.py 50
NoneType: None
2024-08-14 00:25:09,678 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/app.py 62
2024-08-14 00:25:09,744 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/app.py 74
2024-08-14 00:25:09,800 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/app.py 82
2024-08-14 00:25:09,801 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/app.py 95
2024-08-14 00:25:09,801 INFO App created successfully: /home/frank/virtual_doctor_backend/app.py 105
2024-08-14 00:25:44,887 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/app.py 32
2024-08-14 00:25:44,889 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/app.py 50
NoneType: None
2024-08-14 00:25:44,890 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/app.py 62
2024-08-14 00:25:44,938 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/app.py 74
2024-08-14 00:25:44,954 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/app.py 82
2024-08-14 00:25:44,955 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/app.py 95
2024-08-14 00:25:44,955 INFO App created successfully: /home/frank/virtual_doctor_backend/app.py 105
2024-08-14 00:30:01,804 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 32
2024-08-14 00:30:01,804 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 50
2024-08-14 00:30:01,804 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 62
2024-08-14 00:30:01,877 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 74
2024-08-14 00:30:01,901 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 82
2024-08-14 00:30:01,901 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 95
2024-08-14 00:30:01,902 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 105
2024-08-18 15:43:53,682 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 43
2024-08-18 15:43:53,702 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 61
2024-08-18 15:43:53,703 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 73
2024-08-18 15:43:54,220 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 85
2024-08-18 15:43:54,256 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 93
2024-08-18 15:43:54,256 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 106
2024-08-18 15:43:54,257 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 116
2024-08-18 15:43:56,694 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 43
2024-08-18 15:43:56,695 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 61
2024-08-18 15:43:56,695 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 73
2024-08-18 16:14:52,905 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 45
2024-08-18 16:14:52,906 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 63
2024-08-18 16:14:52,906 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 75
2024-08-18 16:14:53,113 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 87
2024-08-18 16:14:53,170 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 95
2024-08-18 16:14:53,171 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 108
2024-08-18 16:14:53,171 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 118
2024-08-18 16:14:55,408 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 45
2024-08-18 16:14:55,408 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 63
2024-08-18 16:14:55,408 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 75
2024-08-18 16:14:55,597 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 87
2024-08-18 16:14:55,644 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 95
2024-08-18 16:14:55,644 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 108
2024-08-18 16:14:55,644 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 118
2024-08-18 16:25:06,204 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 45
2024-08-18 16:25:06,204 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 63
2024-08-18 16:25:06,205 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 75
2024-08-18 16:25:06,445 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 87
2024-08-18 16:25:06,499 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 95
2024-08-18 16:25:06,500 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 108
2024-08-18 16:25:06,500 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 118
2024-08-18 18:10:15,482 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 42
2024-08-18 18:10:15,482 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 60
2024-08-18 18:10:15,483 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 72
2024-08-18 18:10:15,675 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 84
2024-08-18 18:10:15,704 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 92
2024-08-18 18:10:15,705 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 105
2024-08-18 18:10:15,705 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 115
2024-08-18 18:10:17,781 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 42
2024-08-18 18:10:17,782 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 60
2024-08-18 18:10:17,782 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 72
2024-08-18 18:10:17,973 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 84
2024-08-18 18:10:18,003 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 92
2024-08-18 18:10:18,004 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 105
2024-08-18 18:10:18,004 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 1152024-08-18 19:31:25,175 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 42
2024-08-18 19:31:25,176 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 60
2024-08-18 19:31:25,176 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 72
2024-08-18 19:31:25,450 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 84
2024-08-18 19:31:25,502 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 92
2024-08-18 19:31:25,503 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 105
2024-08-18 19:31:25,503 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 115
2024-08-18 19:31:29,251 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 42
2024-08-18 19:31:29,252 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 60
2024-08-18 19:31:29,253 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 72
2024-08-18 19:31:29,572 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 84
2024-08-18 19:31:29,642 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 92
2024-08-18 19:31:29,643 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 105
2024-08-18 19:31:29,644 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 115
2024-08-18 19:32:58,032 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 42
2024-08-18 19:32:58,033 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 60
2024-08-18 19:32:58,033 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 72
2024-08-18 19:32:58,360 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 84
2024-08-18 19:32:58,427 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 92
2024-08-18 19:32:58,428 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 105
2024-08-18 19:32:58,428 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 115
2024-08-18 19:49:05,216 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 41
2024-08-18 19:49:05,217 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 59
2024-08-18 19:49:05,218 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 71
2024-08-18 19:49:05,573 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 83
2024-08-18 19:49:05,648 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 91
2024-08-18 19:49:05,649 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 104
2024-08-18 19:49:05,650 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 115
2024-08-18 20:11:52,482 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 41
2024-08-18 20:11:52,484 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 59
2024-08-18 20:11:52,485 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 71
2024-08-18 20:11:52,828 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 83
2024-08-18 20:11:52,886 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 91
2024-08-18 20:11:52,887 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 104
2024-08-18 20:11:52,888 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 114
2024-08-18 20:11:57,361 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 41
2024-08-18 20:11:57,370 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 59
2024-08-18 20:11:57,370 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 71
2024-08-18 20:11:57,762 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 83
2024-08-18 20:11:57,836 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 91
2024-08-18 20:11:57,837 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 104
2024-08-18 20:11:57,838 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 114
2024-08-18 20:16:08,459 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 41
2024-08-18 20:16:08,460 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 59
2024-08-18 20:16:08,461 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 71
2024-08-18 20:16:09,206 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 83
2024-08-18 20:16:09,298 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 91
2024-08-18 20:16:09,301 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 104
2024-08-18 20:16:09,301 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 114
2024-08-18 20:18:13,470 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 41
2024-08-18 20:18:13,471 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 59
2024-08-18 20:18:13,472 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 71
2024-08-18 20:18:14,029 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 83
2024-08-18 20:18:14,139 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 91
2024-08-18 20:18:14,141 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 104
2024-08-18 20:18:14,143 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 114
2024-08-18 20:51:23,395 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 41
2024-08-18 20:51:23,395 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 59
2024-08-18 20:51:23,396 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 71
2024-08-18 20:51:23,496 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 83
2024-08-18 20:51:23,510 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 91
2024-08-18 20:51:23,510 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 104
2024-08-18 20:51:23,510 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 114
2024-08-18 20:54:26,762 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 41
2024-08-18 20:54:26,762 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 59
2024-08-18 20:54:26,762 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 71
2024-08-18 20:54:26,873 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 83
2024-08-18 20:54:26,897 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 91
2024-08-18 20:54:26,898 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 104
2024-08-18 20:54:26,898 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 114
2024-08-18 20:54:48,681 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 41
2024-08-18 20:54:48,681 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 59
2024-08-18 20:54:48,681 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 71
2024-08-18 20:54:48,776 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 83
2024-08-18 20:54:48,790 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 91
2024-08-18 20:54:48,791 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 104
2024-08-18 20:54:48,791 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 114
2024-08-18 20:54:49,880 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 41
2024-08-18 20:54:49,881 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 59
2024-08-18 20:54:49,881 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 71
2024-08-18 20:54:49,992 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 83
2024-08-18 20:54:50,012 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 91
2024-08-18 20:54:50,012 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 104
2024-08-18 20:54:50,012 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 114
2024-08-18 20:59:36,408 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 41
2024-08-18 20:59:36,408 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 59
2024-08-18 20:59:36,408 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 71
2024-08-18 20:59:36,500 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 83
2024-08-18 20:59:36,514 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 91
2024-08-18 20:59:36,514 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 104
2024-08-18 20:59:36,514 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 114
2024-08-18 21:06:34,541 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 41
2024-08-18 21:06:34,541 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 59
2024-08-18 21:06:34,541 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 71
2024-08-18 21:06:34,639 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 83
2024-08-18 21:06:34,653 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 91
2024-08-18 21:06:34,654 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 104
2024-08-18 21:06:34,654 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 114
2024-08-18 21:07:16,583 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 41
2024-08-18 21:07:16,584 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 59
2024-08-18 21:07:16,584 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 71
2024-08-18 21:07:16,686 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 83
2024-08-18 21:07:16,702 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 91
2024-08-18 21:07:16,702 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 104
2024-08-18 21:07:16,702 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 114
2024-08-18 21:08:58,328 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 41
2024-08-18 21:08:58,328 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 59
2024-08-18 21:08:58,328 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 71
2024-08-18 21:08:58,425 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 83
2024-08-18 21:08:58,445 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 91
2024-08-18 21:08:58,445 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 104
2024-08-18 21:08:58,445 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 114
2024-08-18 21:13:46,045 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 41
2024-08-18 21:13:46,045 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 59
2024-08-18 21:13:46,045 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 71
2024-08-18 21:13:46,147 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 83
2024-08-18 21:13:46,161 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 91
2024-08-18 21:13:46,162 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 104
2024-08-18 21:13:46,162 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 114
2024-08-18 21:14:52,644 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 41
2024-08-18 21:14:52,644 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 59
2024-08-18 21:14:52,644 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 71
2024-08-18 21:14:52,768 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 83
2024-08-18 21:14:52,787 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 91
2024-08-18 21:14:52,787 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 104
2024-08-18 21:14:52,787 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 114
2024-08-18 21:15:12,398 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 41
2024-08-18 21:15:12,398 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 59
2024-08-18 21:15:12,399 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 71
2024-08-18 21:15:12,502 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 83
2024-08-18 21:15:12,519 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 91
2024-08-18 21:15:12,519 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 104
2024-08-18 21:15:12,519 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 114
2024-08-18 21:15:28,076 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 41
2024-08-18 21:15:28,076 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 59
2024-08-18 21:15:28,077 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 71
2024-08-18 21:15:28,181 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 83
2024-08-18 21:15:28,196 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 91
2024-08-18 21:15:28,197 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 104
2024-08-18 21:15:28,197 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 114
2024-08-18 21:16:46,112 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/app.py 41
2024-08-18 21:16:46,113 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/app.py 59
2024-08-18 21:16:46,114 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/app.py 71
2024-08-18 21:16:46,159 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/app.py 83
2024-08-18 21:16:46,178 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/app.py 91
2024-08-18 21:16:46,178 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/app.py 104
2024-08-18 21:16:46,178 INFO App created successfully: /home/frank/virtual_doctor_backend/app.py 114
2024-08-18 21:17:14,617 ERROR An error occored while checking the password: /home/frank/virtual_doctor_backend/models/base_model.py 20
Traceback (most recent call last):
  File "/home/frank/virtual_doctor_backend/models/base_model.py", line 18, in check_pwd
    res = bcrypt.checkpw(password.encode('UTF-8'), hashed_pwd)
  File "/usr/lib/python3/dist-packages/bcrypt/__init__.py", line 120, in checkpw
    raise TypeError("Unicode-objects must be encoded before checking")
TypeError: Unicode-objects must be encoded before checking
2024-08-18 21:17:34,248 ERROR An error occored while checking the password: /home/frank/virtual_doctor_backend/models/base_model.py 20
Traceback (most recent call last):
  File "/home/frank/virtual_doctor_backend/models/base_model.py", line 18, in check_pwd
    res = bcrypt.checkpw(password.encode('UTF-8'), hashed_pwd)
  File "/usr/lib/python3/dist-packages/bcrypt/__init__.py", line 120, in checkpw
    raise TypeError("Unicode-objects must be encoded before checking")
TypeError: Unicode-objects must be encoded before checking
2024-08-18 21:19:43,665 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 41
2024-08-18 21:19:43,666 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 59
2024-08-18 21:19:43,666 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 71
2024-08-18 21:19:43,763 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 83
2024-08-18 21:19:43,777 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 91
2024-08-18 21:19:43,777 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 104
2024-08-18 21:19:43,778 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 114
2024-08-18 21:21:05,280 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 41
2024-08-18 21:21:05,280 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 59
2024-08-18 21:21:05,281 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 71
2024-08-18 21:21:05,373 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 83
2024-08-18 21:21:05,387 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 91
2024-08-18 21:21:05,387 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 104
2024-08-18 21:21:05,388 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 114
2024-08-18 21:22:11,192 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 41
2024-08-18 21:22:11,192 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 59
2024-08-18 21:22:11,193 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 71
2024-08-18 21:22:11,293 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 83
2024-08-18 21:22:11,308 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 91
2024-08-18 21:22:11,308 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 104
2024-08-18 21:22:11,308 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 114
2024-08-18 21:23:48,749 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 41
2024-08-18 21:23:48,750 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 59
2024-08-18 21:23:48,750 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 71
2024-08-18 21:23:48,859 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 83
2024-08-18 21:23:48,875 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 91
2024-08-18 21:23:48,875 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 104
2024-08-18 21:23:48,875 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 114
2024-08-18 21:26:29,130 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 41
2024-08-18 21:26:29,130 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 59
2024-08-18 21:26:29,130 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 71
2024-08-18 21:26:29,234 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 83
2024-08-18 21:26:29,257 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 91
2024-08-18 21:26:29,258 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 104
2024-08-18 21:26:29,258 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 114
2024-08-18 21:39:07,893 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/app.py 41
2024-08-18 21:39:07,894 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/app.py 59
2024-08-18 21:39:07,894 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/app.py 71
2024-08-18 21:39:07,935 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/app.py 83
2024-08-18 21:39:07,951 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/app.py 91
2024-08-18 21:39:07,951 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/app.py 104
2024-08-18 21:39:07,951 INFO App created successfully: /home/frank/virtual_doctor_backend/app.py 114
2024-08-18 22:15:37,823 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 41
2024-08-18 22:15:37,824 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 59
2024-08-18 22:15:37,824 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 71
2024-08-18 22:15:37,920 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 83
2024-08-18 22:15:37,934 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 91
2024-08-18 22:15:37,934 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 104
2024-08-18 22:15:37,934 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 114
2024-08-18 22:15:48,965 ERROR patient registration failed: /home/frank/virtual_doctor_backend/api/auth.py 119
Traceback (most recent call last):
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1970, in _exec_single_context
    self.dialect.do_execute(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '12354228587' for key 'patients.contact'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/frank/virtual_doctor_backend/api/auth.py", line 116, in register
    db.session.commit()
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4296, in flush
    self._flush(objects)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4431, in _flush
    with util.safe_reraise():
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4392, in _flush
    flush_context.execute()
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1421, in execute
    return meth(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1643, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1849, in _execute_context
    return self._exec_single_context(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1989, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2356, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1970, in _exec_single_context
    self.dialect.do_execute(
  File "/home/frank/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/frank/.local/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.IntegrityError: (pymysql.err.IntegrityError) (1062, "Duplicate entry '12354228587' for key 'patients.contact'")
[SQL: INSERT INTO patients (patient_uuid, name, email, contact, birthday, gender, password, reg_date) VALUES (%(patient_uuid)s, %(name)s, %(email)s, %(contact)s, %(birthday)s, %(gender)s, %(password)s, %(reg_date)s)]
[parameters: {'patient_uuid': 'be478c6f-35a4-4170-9f29-22eff4ad4aaa', 'name': 'qwert', 'email': 'iuytgt@gail.cojjjm', 'contact': '12354228587', 'birthday': '2004-11-11', 'gender': 'male', 'password': b'$2b$12$UC7VI/eUwyiZ2sMN1UdgYewJljCrjzAc21AQfty.fOjpttf7AwHfq', 'reg_date': datetime.datetime(2024, 8, 18, 22, 15, 48, 364869)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-08-18 22:16:22,519 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/app.py 41
2024-08-18 22:16:22,521 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/app.py 59
2024-08-18 22:16:22,522 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/app.py 71
2024-08-18 22:16:22,585 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/app.py 83
2024-08-18 22:16:22,612 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/app.py 91
2024-08-18 22:16:22,612 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/app.py 104
2024-08-18 22:16:22,613 INFO App created successfully: /home/frank/virtual_doctor_backend/app.py 114
2024-08-18 22:17:16,175 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/./app.py 41
2024-08-18 22:17:16,175 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/./app.py 59
2024-08-18 22:17:16,175 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/./app.py 71
2024-08-18 22:17:16,282 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/./app.py 83
2024-08-18 22:17:16,299 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/./app.py 91
2024-08-18 22:17:16,299 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/./app.py 104
2024-08-18 22:17:16,299 INFO App created successfully: /home/frank/virtual_doctor_backend/./app.py 114
2024-08-19 02:02:32,321 ERROR An error occored while checking the password: /home/frank/virtual_doctor_backend/models/base_model.py 20
Traceback (most recent call last):
  File "/home/frank/virtual_doctor_backend/models/base_model.py", line 18, in check_pwd
    res = bcrypt.checkpw(password.encode('UTF-8'), hashed_pwd)
  File "/usr/lib/python3/dist-packages/bcrypt/__init__.py", line 120, in checkpw
    raise TypeError("Unicode-objects must be encoded before checking")
TypeError: Unicode-objects must be encoded before checking
2024-08-19 02:02:52,377 ERROR An error occored while checking the password: /home/frank/virtual_doctor_backend/models/base_model.py 20
Traceback (most recent call last):
  File "/home/frank/virtual_doctor_backend/models/base_model.py", line 18, in check_pwd
    res = bcrypt.checkpw(password.encode('UTF-8'), hashed_pwd)
  File "/usr/lib/python3/dist-packages/bcrypt/__init__.py", line 120, in checkpw
    raise TypeError("Unicode-objects must be encoded before checking")
TypeError: Unicode-objects must be encoded before checking
2024-08-19 02:03:12,053 ERROR An error occored while checking the password: /home/frank/virtual_doctor_backend/models/base_model.py 20
Traceback (most recent call last):
  File "/home/frank/virtual_doctor_backend/models/base_model.py", line 18, in check_pwd
    res = bcrypt.checkpw(password.encode('UTF-8'), hashed_pwd)
  File "/usr/lib/python3/dist-packages/bcrypt/__init__.py", line 120, in checkpw
    raise TypeError("Unicode-objects must be encoded before checking")
TypeError: Unicode-objects must be encoded before checking
2024-08-19 02:03:14,686 ERROR An error occored while checking the password: /home/frank/virtual_doctor_backend/models/base_model.py 20
Traceback (most recent call last):
  File "/home/frank/virtual_doctor_backend/models/base_model.py", line 18, in check_pwd
    res = bcrypt.checkpw(password.encode('UTF-8'), hashed_pwd)
  File "/usr/lib/python3/dist-packages/bcrypt/__init__.py", line 120, in checkpw
    raise TypeError("Unicode-objects must be encoded before checking")
TypeError: Unicode-objects must be encoded before checking
2024-08-19 02:04:41,601 INFO Logging setup successfully: /home/frank/virtual_doctor_backend/app.py 41
2024-08-19 02:04:41,601 INFO Uploads directory set up successfully: /home/frank/virtual_doctor_backend/app.py 59
2024-08-19 02:04:41,602 INFO DataBase set up successfully: /home/frank/virtual_doctor_backend/app.py 71
2024-08-19 02:04:41,636 INFO Migrations set up successfully: /home/frank/virtual_doctor_backend/app.py 83
2024-08-19 02:04:41,651 INFO Blueprints registered successfully: /home/frank/virtual_doctor_backend/app.py 91
2024-08-19 02:04:41,652 INFO Mail service setup successfully: /home/frank/virtual_doctor_backend/app.py 104
2024-08-19 02:04:41,652 INFO App created successfully: /home/frank/virtual_doctor_backend/app.py 114
2024-08-19 02:05:12,190 ERROR An error occored while checking the password: /home/frank/virtual_doctor_backend/models/base_model.py 20
Traceback (most recent call last):
  File "/home/frank/virtual_doctor_backend/models/base_model.py", line 18, in check_pwd
    res = bcrypt.checkpw(password.encode('UTF-8'), hashed_pwd)
  File "/usr/lib/python3/dist-packages/bcrypt/__init__.py", line 120, in checkpw
    raise TypeError("Unicode-objects must be encoded before checking")
TypeError: Unicode-objects must be encoded before checking
